project:
  type: website

website:
  title: "云计算原理与实践"
  search: false
  navbar:
    pinned: true
    left:
      - text: "PDF 教材"
        href: index.qmd
    right:
      - text: "课程主页"
        href: https://hnu-cloudcomputing.github.io/cloudcompute-pages/
      - text: "Markdown 版"
        href: https://hnu-cloudcomputing.github.io/CloudComputingMarkdown/
      - text: "课程课件"
        href: https://github.com/HNU-CloudComputing/CloudComputingCoursePPT
  page-footer:
    left: "Copyright © 2026 GuoLab. All Rights Reserved."
    right: "湖南大学 HNU GuoLab"

format:
  html:
    theme:
      - litera
      - theme.scss
    toc: false
    page-layout: custom
    smooth-scroll: true
    link-external-newwindow: true
